const constants = {
  GET_CONTACTS: 'GET_CONTACTS',
  GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
  GET_CONTACT: 'GET_CONTACT',
  GET_CONTACT_SUCCESS: 'GET_CONTACT_SUCCESS',
  GET_DEALS: 'GET_DEALS',
  GET_DEALS_SUCCESS: 'GET_DEALS_SUCCESS',
  GET_CONTACTTAGNUMBERS: 'GET_CONTACTTAGNUMBERS',
  GET_CONTACTTAGNUMBERS_SUCCESS: 'GET_CONTACTTAGNUMBERS_SUCCESS',
  GET_CONTACTTAG: 'GET_CONTACTTAG',
  GET_CONTACTTAG_SUCCESS: 'GET_CONTACTTAG_SUCCESS',
}

export default constants;