const constants = {
  GET_CONTACTS: 'GET_CONTACTS',
  GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
  GET_CONTACT: 'GET_CONTACT',
  GET_CONTACT_SUCCESS: 'GET_CONTACT_SUCCESS',
  GET_CONTACT_DEALS: 'GET_CONTACT_DEALS',
  GET_CONTACT_DEALS_SUCCESS: 'GET_CONTACT_DEALS_SUCCESS',
  GET_CONTACT_TAGS: 'GET_CONTACT_TAGS',
  GET_CONTACT_TAGS_SUCCESS: 'GET_CONTACT_TAGS_SUCCESS',
  GET_CONTACT_TAG_NAME: 'GET_CONTACT_TAG_NAME',
  GET_CONTACT_TAG_NAME_SUCCESS: 'GET_CONTACT_TAG_NAME_SUCCESS',
}

export default constants;